### ISSUE TITLE
Error when using require

### ISSUE THREAD

**Issue by talmog** [eder/express-inline-css-amp#1]
Hi, 
I am trying to use this repo, but I am getting an error when I try to require (not import) your lib:
in my app.js:
```
var inlineCSSAMP = require('express-inline-css-amp');
```

Error in my console:
```
module.js:457
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/classCallCheck'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/***/Documents/dev/***/node_modules/express-inline-css-amp/lib/index.js:8:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

I generated this project using express generator.

**Comment by eder** [comment]
@talmog Sorry .... I Fixed this, when you can test, you can send me comments?

**Comment by talmog** [comment]
Working like magic! thanks @eder
